# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-11-08 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpifoodapp', '0001_auto_20201108_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
