# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-11-01 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpifoodapp', '0003_order_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.IntegerField(choices=[(1, 'Cooking'), (2, 'Ready'), (3, 'On the way'), (4, 'Delivered'), (5, 'Accepted')]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.IntegerField(choices=[(1, 'Pizza'), (2, 'Savoyard'), (3, 'Meat'), (4, 'Fast-food'), (5, 'Gastro'), (6, 'Asian'), (7, 'Modern'), (8, 'Burger'), (9, 'Fondu'), (10, 'Italian'), (11, 'Snack'), (12, 'French'), (13, 'Alsacien'), (14, 'Fish'), (15, 'Wine-bar'), (16, 'Tapas'), (17, 'Breakfast')], default=0),
        ),
    ]
